openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8000/api/v1
    description: local server
  - url: http://example.com
    description: Optional server description, e.g. Internal staging server for testing

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 

security:
  - basicAuth: []           
paths:
  /users/register:
    post:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string 
                password:
                  type: string
                role:
                  type: string
                profile:
                  type: string
                  format: binary

      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /users/login:
    post:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      tags:
      - userLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string 
                password:
                  type: string

      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string 
               
  /users/logout:
    post:
      summary: logout users.
      description: Optional extended description in CommonMark or HTML.
      tags:
      - userLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string   

  /users/get-refreshtokan:
    post:
      summary: get-refreshtokan.
      description: Optional extended description in CommonMark or HTML.
      tags:
      - user

      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string 
                 
  /users/google:
    get:
      summary: google login.
      description: Optional extended description in CommonMark or HTML.
      tags:
      - user

      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string  

  /categories/list-categories:
    get:
      summary: google login.
      description: pagesize
      tags:
      - user
      

      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string   


  /categories/update-category/{category_id}:
    put:
      summary: google login.
      description: pagesize
      tags:
      - user
      parameters:
        - in: path
          name: category_id
          schema:
            type: integer
          required: true
          description: Update category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string     
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string              
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string                                                                                                                                                                                                                           0                